# ==============================================================================
# PeerCraft Primary Node (Overworld Instance) Server Properties
# ==============================================================================
server-port=25565
online-mode=false
allow-nether=true
allow-end=true
view-distance=8
simulation-distance=6
network-compression-threshold=256
max-players=20
enable-rcon=true
rcon.port=25575
rcon.password=PEERCRAFT_INTERNAL_RCON_PASS_SECURE
sync-chunk-writes=true
level-name=world
gamemode=survival
difficulty=hard
spawn-protection=0
enable-command-block=true
white-list=false
enforce-whitelist=false
max-world-size=29999984
hide-online-players=false
enable-status=true
rate-limit=0
